In [2]:
import pandas as pd
import numpy as np
NaN = np.nan

In [3]:
# unicodeの表
# http://www.unicode.org/Public/MAPPINGS/OBSOLETE/EASTASIA/JIS/JIS0208.TXT
    
df = pd.read_csv("data/JIS0208-2015-unicode.txt",
                   sep='\t',
                   skiprows=63,
                   names=('SJIS', 'JIS', 'Unicode', 'Comment'))
df.info()

df[0:5]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6879 entries, 0 to 6878
Data columns (total 4 columns):
SJIS       6879 non-null object
JIS        6879 non-null object
Unicode    6879 non-null object
Comment    6879 non-null object
dtypes: object(4)
memory usage: 215.0+ KB

     SJIS     JIS Unicode                  Comment
0  0x8140  0x2121  0x3000      # IDEOGRAPHIC SPACE
1  0x8141  0x2122  0x3001      # IDEOGRAPHIC COMMA
2  0x8142  0x2123  0x3002  # IDEOGRAPHIC FULL STOP
3  0x8143  0x2124  0xFF0C        # FULLWIDTH COMMA
4  0x8144  0x2125  0xFF0E    # FULLWIDTH FULL STOP

In [23]:
dfDai1Suijyun = df.query("'0x3000' <= JIS < '0x5000'")  
dfDai1Suijyun.info()
#第一水準 2965

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2965 entries, 524 to 3488
Data columns (total 4 columns):
SJIS       2965 non-null object
JIS        2965 non-null object
Unicode    2965 non-null object
Comment    2965 non-null object
dtypes: object(4)
memory usage: 115.8+ KB

In [7]:
df.query("JIS=='0x2121'")

     SJIS     JIS Unicode              Comment
0  0x8140  0x2121  0x3000  # IDEOGRAPHIC SPACE

In [ ]:
df30 = df.query("'0x3000' <= JIS < '0x3100'"); df30.info()
df31 = df.query("'0x3100' <= JIS < '0x3200'"); df31.info()  
df32 = df.query("'0x3200' <= JIS < '0x3300'"); df32.info()  
df33 = df.query("'0x3300' <= JIS < '0x3400'"); df33.info()  
df34 = df.query("'0x3400' <= JIS < '0x3500'"); df34.info()  
df35 = df.query("'0x3500' <= JIS < '0x3600'"); df35.info()  
df36 = df.query("'0x3600' <= JIS < '0x3700'"); df36.info()
df37 = df.query("'0x3700' <= JIS < '0x3800'"); df37.info()  
df38 = df.query("'0x3800' <= JIS < '0x3900'"); df38.info()  
df39 = df.query("'0x3900' <= JIS < '0x3A00'"); df39.info()  
df3A = df.query("'0x3A00' <= JIS < '0x3B00'"); df3A.info()  
df3B = df.query("'0x3B00' <= JIS < '0x3C00'"); df3B.info()  
df3C = df.query("'0x3C00' <= JIS < '0x3D00'"); df3C.info()
df3D = df.query("'0x3D00' <= JIS < '0x3E00'"); df3D.info()  
df3E = df.query("'0x3E00' <= JIS < '0x3F00'"); df3E.info()  
df3F = df.query("'0x3F00' <= JIS < '0x4000'"); df3F.info()

In [18]:
df40 = df.query("'0x4000' <= JIS < '0x4100'"); df40.info()
df41 = df.query("'0x4100' <= JIS < '0x4200'"); df41.info()  
df42 = df.query("'0x4200' <= JIS < '0x4300'"); df42.info()  
df43 = df.query("'0x4300' <= JIS < '0x4400'"); df43.info()  
df44 = df.query("'0x4400' <= JIS < '0x4500'"); df44.info()  
df45 = df.query("'0x4500' <= JIS < '0x4600'"); df45.info()  
df46 = df.query("'0x4600' <= JIS < '0x4700'"); df46.info()
df47 = df.query("'0x4700' <= JIS < '0x4800'"); df47.info()  
df48 = df.query("'0x4800' <= JIS < '0x4900'"); df48.info()  
df49 = df.query("'0x4900' <= JIS < '0x4A00'"); df49.info()  
df4A = df.query("'0x4A00' <= JIS < '0x4B00'"); df4A.info()  
df4B = df.query("'0x4B00' <= JIS < '0x4C00'"); df4B.info()  
df4C = df.query("'0x4C00' <= JIS < '0x4D00'"); df4C.info()
df4D = df.query("'0x4D00' <= JIS < '0x4E00'"); df4D.info()  
df4E = df.query("'0x4E00' <= JIS < '0x4F00'"); df4E.info()  
df4F = df.query("'0x4F00' <= JIS < '0x5000'"); df4F.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 94 entries, 2028 to 2121
Data columns (total 4 columns):
SJIS       94 non-null object
JIS        94 non-null object
Unicode    94 non-null object
Comment    94 non-null object
dtypes: object(4)
memory usage: 3.7+ KB
<class 'pandas.core.frame.DataFrame'>
Int64Index: 94 entries, 2122 to 2215
Data columns (total 4 columns):
SJIS       94 non-null object
JIS        94 non-null object
Unicode    94 non-null object
Comment    94 non-null object
dtypes: object(4)
memory usage: 3.7+ KB
<class 'pandas.core.frame.DataFrame'>
Int64Index: 94 entries, 2216 to 2309
Data columns (total 4 columns):
SJIS       94 non-null object
JIS        94 non-null object
Unicode    94 non-null object
Comment    94 non-null object
dtypes: object(4)
memory usage: 3.7+ KB
<class 'pandas.core.frame.DataFrame'>
Int64Index: 94 entries, 2310 to 2403
Data columns (total 4 columns):
SJIS       94 non-null object
JIS        94 non-null object
Unicode    94 non-null object
Comment    94 non-null object
dtypes: object(4)
memory usage: 3.7+ KB
<class 'pandas.core.frame.DataFrame'>
Int64Index: 94 entries, 2404 to 2497
Data columns (total 4 columns):
SJIS       94 non-null object
JIS        94 non-null object
Unicode    94 non-null object
Comment    94 non-null object
dtypes: object(4)
memory usage: 3.7+ KB
<class 'pandas.core.frame.DataFrame'>
Int64Index: 94 entries, 2498 to 2591
Data columns (total 4 columns):
SJIS       94 non-null object
JIS        94 non-null object
Unicode    94 non-null object
Comment    94 non-null object
dtypes: object(4)
memory usage: 3.7+ KB
<class 'pandas.core.frame.DataFrame'>
Int64Index: 94 entries, 2592 to 2685
Data columns (total 4 columns):
SJIS       94 non-null object
JIS        94 non-null object
Unicode    94 non-null object
Comment    94 non-null object
dtypes: object(4)
memory usage: 3.7+ KB
<class 'pandas.core.frame.DataFrame'>
Int64Index: 94 entries, 2686 to 2779
Data columns (total 4 columns):
SJIS       94 non-null object
JIS        94 non-null object
Unicode    94 non-null object
Comment    94 non-null object
dtypes: object(4)
memory usage: 3.7+ KB
<class 'pandas.core.frame.DataFrame'>
Int64Index: 94 entries, 2780 to 2873
Data columns (total 4 columns):
SJIS       94 non-null object
JIS        94 non-null object
Unicode    94 non-null object
Comment    94 non-null object
dtypes: object(4)
memory usage: 3.7+ KB
<class 'pandas.core.frame.DataFrame'>
Int64Index: 94 entries, 2874 to 2967
Data columns (total 4 columns):
SJIS       94 non-null object
JIS        94 non-null object
Unicode    94 non-null object
Comment    94 non-null object
dtypes: object(4)
memory usage: 3.7+ KB
<class 'pandas.core.frame.DataFrame'>
Int64Index: 94 entries, 2968 to 3061
Data columns (total 4 columns):
SJIS       94 non-null object
JIS        94 non-null object
Unicode    94 non-null object
Comment    94 non-null object
dtypes: object(4)
memory usage: 3.7+ KB
<class 'pandas.core.frame.DataFrame'>
Int64Index: 94 entries, 3062 to 3155
Data columns (total 4 columns):
SJIS       94 non-null object
JIS        94 non-null object
Unicode    94 non-null object
Comment    94 non-null object
dtypes: object(4)
memory usage: 3.7+ KB
<class 'pandas.core.frame.DataFrame'>
Int64Index: 94 entries, 3156 to 3249
Data columns (total 4 columns):
SJIS       94 non-null object
JIS        94 non-null object
Unicode    94 non-null object
Comment    94 non-null object
dtypes: object(4)
memory usage: 3.7+ KB
<class 'pandas.core.frame.DataFrame'>
Int64Index: 94 entries, 3250 to 3343
Data columns (total 4 columns):
SJIS       94 non-null object
JIS        94 non-null object
Unicode    94 non-null object
Comment    94 non-null object
dtypes: object(4)
memory usage: 3.7+ KB
<class 'pandas.core.frame.DataFrame'>
Int64Index: 94 entries, 3344 to 3437
Data columns (total 4 columns):
SJIS       94 non-null object
JIS        94 non-null object
Unicode    94 non-null object
Comment    94 non-null object
dtypes: object(4)
memory usage: 3.7+ KB
<class 'pandas.core.frame.DataFrame'>
Int64Index: 51 entries, 3438 to 3488
Data columns (total 4 columns):
SJIS       51 non-null object
JIS        51 non-null object
Unicode    51 non-null object
Comment    51 non-null object
dtypes: object(4)
memory usage: 2.0+ KB

In [20]:
a = 16*94+15*94
a

2914